M48
; DRILL file {KiCad (6.0.5)} date Mon Feb  6 04:07:21 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-06T04:07:21+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
%
G90
G05
T1
X84.938Y-100.042
X151.17Y-59.342
X151.173Y-100.042
T0
M30
